name: kache_provider
description: Provider state management integration for the Kache Flutter library.
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  kache_flutter: ^0.1.0
  provider: ^6.1.5+1
