name: kache_bloc_example
version: 1.0.0
description: Example application for the Bloc integration provided by Kache.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  kache_bloc: ^1.0.0
  kache_example_support: ^1.0.0

dev_dependencies:
  flutter_cockpit: ^1.1.2
  flutter_test:
    sdk: flutter
  kache: ^1.0.0
  kache_hive_ce: ^1.0.0

flutter:
  uses-material-design: true
