name: kache_bloc_example
description: Example application for the Bloc integration provided by Kache.
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  kache_bloc: ^0.1.0
